config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "users#index"

  # Defines the root path route ("/")

  # root "articles#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :read, :all
    if user.is? :admin
      can :manage, :all
    elsif user.is? :user
      can :manage, Post, user_id: user.id
      can :manage, Comment, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  after_save :update_post_counter
  after_destroy :update_post_counter_after_destroy
  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    Comment.where(post_id: id).order(created_at: :desc).limit(5)
  end

  private

  def update_post_counter
    user.increment!(:posts_counter)
  end

  def update_post_counter_after_destroy
    user.decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # rubocop:disable all
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, class_name: 'Post', dependent: :destroy
  has_many :likes, class_name: 'Like', dependent: :destroy
  has_many :comments, class_name: 'Comment', dependent: :destroy
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  Roles = [ :admin , :user ]

  def is?(requested_role)
    self.role == requested_role.to_s
  end

  def recent_posts
    Post.where(user_id: id).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }
  before_action :update_allowed_parameters, if: :devise_controller?
  add_flash_types :danger, :info, :warning, :success

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :photo, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :email, :photo, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
# this class is for CommentsController
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @current_user = current_user
    @comment = Comment.new
  end

  def create
    @current_user = current_user
    @post_id = params[:post_id]
    @post = Post.find(@post_id)
    comment = Comment.new(comment_params.merge(user: current_user, post_id: @post_id))
    if comment.save
      respond_to do |format|
        format.html do
          redirect_to user_post_path(@post.user_id, @post_id), success: 'Your comment was successfully posted!'
        end
        format.json { render json: comment }
      end
    else
      respond_to do |format|
        format.html do
          flash.now[:danger] = 'Your comment was not posted!'
          render :new
        end
        format.json { render json: comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @current_user = current_user
    @post_id = params[:post_id]
    @post = Post.find(@post_id)
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to user_post_path(@post.user_id, @post_id), success: 'Your comment was successfully deleted!'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post_id = params[:post_id]
    @current_user = current_user

    if liked?
      flash[:danger] = 'You have already liked this post!'
    else
      Like.create(user: current_user, post_id: @post_id)
      flash[:success] = 'You have successfully liked this post!'
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def liked?
    Like.find_by(user: @current_user, post_id: @post_id).present?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :authenticate_user!

  def index
    @current_user = current_user
    @user = User.find_by(id: params[:user_id])
    redirect_to users_path if @user.nil?
    @posts = @user.posts.includes(:comments)

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @posts }
    end
  end

  def show
    @current_user = current_user
    @user = User.find_by(id: params[:user_id])
    redirect_to users_path, danger: "No user was found by given the id: #{params[:user_id]}" if @user.nil?
    @post = @user.posts.find_by(id: params[:id])

    redirect_to user_posts_path(@user.id), danger: "No post was found by given id: #{params[:id]}" if @post.nil?
  end

  def new
    @current_user = current_user
    @post = Post.new
    @user = current_user
  end

  def create
    @current_user = current_user
    redirect_to users_path, danger: "No user was found by given the id: #{params[:user_id]}" if @current_user.nil?
    @post = @current_user.posts.new(post_params)
    if @post.valid?
      @post.save
      redirect_to user_path(@current_user.id), success: 'Post was successfully created'
    else
      flash.now[:danger] = @post.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    @current_user = current_user
    @user = User.find_by(id: params[:user_id])
    redirect_to users_path, danger: "No user was found by given the id: #{params[:user_id]}" if @user.nil?
    @post = @user.posts.find_by(id: params[:id])
    redirect_to user_posts_path(@user.id), danger: "No post was found by given id: #{params[:id]}" if @post.nil?
    @post.destroy
    redirect_to user_posts_path(@user.id), success: 'Post was successfully deleted'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!

  def index
    @current_user = current_user
    @users = User.all

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @users }
    end
  end

  def show
    @current_user = current_user
    @user = User.find_by(id: params[:id])
    redirect_to users_path, danger: "User was not found by given id: #{params[:id]}" if @user.nil?

    @posts = @user&.recent_posts || 'No posts'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/views/application/_comment.html.erb
<li class="list-group-item card">
  <div class="card-header d-flex align-items-center gap-2">
    <%= comment.user.name %>
    <small>
      <%= comment.created_at.strftime("%m/%d/%Y %I:%M %p") %>
    </small>

    <% if can? :destroy, comment %>
    <div class="ms-auto d-inline-block"> 
      <%= button_to "", user_post_comment_path(comment.user_id,comment.post_id,comment.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger fa-solid fa-trash-can d-inline-block ms-auto' %>
    </div>
    <% end %>
  </div>
  <div class="card-body"><%= comment.text %></div>
</li>

app/views/application/_like_comment_links.html.erb
<%= button_to user_post_likes_path(user.id, post.id), method: :post, class: "fa fa-thumbs-up me-2 text-decoration-none border-0 text-primary bg-transparent" do %>
<% end %>
<%= link_to new_user_post_comment_path(user.id, post.id), class: "fa-comment fa-solid text-decoration-none" do %>
<% end %>

app/views/application/_post.html.erb
<article class="card" >
  <%= link_to user_post_path(@user.id, post.id), class: "text-decoration-none" do %>
    <div class="card-header d-flex">
      <h3>
        <%= post.title %>
      </h3>

      <% if can? :destroy, post %>
        <div class="ms-auto d-inline-block"> 
          <%= button_to "", user_post_path(post.user_id,post.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger fa-solid fa-trash-can d-inline-block ms-auto' %>
        </div>
      <% end %>
    </div>
    <div class="card-body">
      <p class="card-text">
        <%= post.text[0..100] + "..." %>
      </p>
    </div>
    <div class="card-footer d-flex">
    <div class="d-inline-flex align-items-center">
      <%= render "like_comment_links", user: @user, post: post%>
    </div>
    <span class="ms-auto ">
      Comments: <%= post.comments_counter %>,
      Likes: <%= post.likes_counter %>
    </span>
  </div>
  <% end %>
</article>

app/views/application/_user.html.erb
<%= link_to user_path(user.id), class: "text-decoration-none" do %>
<li class="list-group-item rounded border-top nav-link">
  <img src="<%= user.photo %>" alt="user profile picture" width="100"/>
    <h2 class="h2 d-inline-block"><%= user.name %></h2>
    <p class="d-inline-block">
      Number of posts:<%= user.posts_counter %>
    </p>
</li>
<% end %>

app/views/comments/new.html.erb
<%= form_with model: @comment, url: user_post_comments_path do |form| %>
  <div class="mb-3">
    <%= form.label :text, "Comment" %>
    <%= form.text_area :text, required: true, class: "form-control" %>
  </div>
  <%= form.submit "Comment", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Blog App</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-primary px-lg-5 px-2 py-2">
      <% if user_signed_in? %>
      <%= link_to "Home", root_path, class: 'navbar-brand' %>
      <%= link_to "My Profile", user_posts_path(current_user.id), class: "nav-link text-white" %> 
      <%= link_to "Create a new post", new_user_post_path(current_user.id), class: "nav-link text-white" %>
      <%= image_tag current_user&.photo, class: "rounded-circle ms-auto", style: "width:60px;aspect-ratio:1;" %>
      <span class="nav-link text-white"><%= current_user.name %></span>
      <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-secondary me-2' %>
      <%= button_to 'Log Out', destroy_user_session_path, class: 'btn btn-danger', :method => 'delete' %>
      <% else %>
      <div class="ms-auto">
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary" %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success" %>
      </div>
      <% end %>
      </div>
    </nav>
    <div class="p-lg-5 py-3 px-2">
    <% flash.each do |type, msg| type = 'danger' if type == 'alert'%>
    <% type = 'warning' if type == 'notice'  %>
      <div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
          <%= msg %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/posts/index.html.erb
<main class="d-grid gap-3">
  <%= render "user", user: @user %>
  <% @posts.each do |post| %>
    <div>
      <%= render "post", post: post %>
      <ul class="list-group border-bottom">
        <%= render partial: "comment", collection: post.comments[0..4] %>
      </ul>
    </div>
  <% end %>
</main>

app/views/posts/new.html.erb
<%= form_with model: @post, url: user_posts_path, local: true do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control", placeholder: "This is my first post!" %>
  </div>
  <div class="mb-3">
    <%= form.label :text, class: "form-label" %>
    <%= form.text_area :text, class: "form-control", placeholder: "Hello world!", required: true %>
  </div>
  <%= form.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<article class="card">
  <div class="card-header d-flex justify-content-between align-items-center flex-column flex-sm-row">
    <div class="d-flex align-items-center gap-1">
      <h4 ><%= @post.title %> </h4>
      <span class="h4">By</span>
      <h5 class="h4"><%= @post.user.name %></h5>
    </div>
    <div>
      Comments: <%= @post.comments.count %>,
      Likes: <%= @post.likes.count %>


      <% if can? :destroy, @post %>
        <div class="ms-3 d-inline-block"> 
          <%= button_to "", user_post_path(@post.user_id,@post.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger fa-solid fa-trash-can d-inline-block ms-auto' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="card-body">
    <%= @post.text %>
  </div>
  <div class="card-footer d-flex align-items-center">
    <%= render "like_comment_links", post: @post, user: @user %>
  </div>
</article>
<div class="border-bottom">
  <%= render partial: "comment", collection: @post.comments %>
</div>

app/views/users/index.html.erb
<ul class="list-group">
<div class="d-grid gap-3"><%= render partial: "user", collection: @users %> </div>
</ul>

app/views/users/show.html.erb
<main class="d-grid gap-3">
  <%= render "user", user: @user %>
    <div class="card mb-3">
      <div class="card-header">
        <h2>Bio</h2>
      </div>
      <div class="card-body">
        <p class="card-text">
          <%= @user.bio %>
        </p>
      </div>
    </div>

    <div class="posts_container">
      <% @posts.each do |post| %>
        <%= render "post", post: post %>
        <% post.comments.each do |comment| %>
          <%= render "comment", comment: comment %>
        <% end %>
      <% end %>
    </div>
    <%= link_to "See all posts", user_posts_path(@user.id), class: "btn btn-primary mx-auto", style: "width: fit-content" %>
</main>